### ISSUE TITLE
New feature to be able to turn individual days on or off

### ISSUE THREAD

**Issue by michelebossa** [michelebossa/HA-Scheduler#1]
AJStubbsy
Adam Stubbs Request

I was hoping for a feature to be able to turn individual days on or off, without having to remove a time. The scenario could be having the lights come on at a certain time but knowing you’ll be away on a particular day, you turn it off for that day and then put it back on again, when your schedule returns to normal.

I realise I could just change the time and so very happy to be using this as it is.

Thanks again.

My proposal
<img width="539" alt="proprosal" src="https://user-images.githubusercontent.com/38975058/79227178-cd534200-7e5f-11ea-97f4-276ec6170155.png">

**Comment by AJStubbsy** [comment]
It could also be handy to enable/disable from the home screen. Not sure how practical that is. I feel so cheeky requesting changes to something you've only just posted about. I hope you don't mind. Your addon has allowed me to remove lines and lines of code from automations.yaml, it's really brilliant and I can't thank you enough.

![image](https://user-images.githubusercontent.com/10088946/79230605-c545d300-7e5c-11ea-9962-8817b211b2dc.png)

**Comment by michelebossa** [comment]
I prefer don't give the possibility to edit into main screen to prevent accidentally change.

To kept more clear the main section i'm working on color of header to understand the activation of days.

![image](https://user-images.githubusercontent.com/38975058/79252788-77dc5c80-7e82-11ea-9c1e-351f8fe9890c.png)

The modify it is almost completed but i need more times to test.

**Comment by michelebossa** [comment]
Added into V0.5
