### ISSUE TITLE
Theme adoption

### ISSUE THREAD

**Issue by AJStubbsy** [michelebossa/HA-Scheduler#2]
I'm loving using this scheduler! Would it be possible for the add-on to use the colours of the users Theme, or maybe have a dark mode?

**Comment by michelebossa** [comment]
Hi,
I'm adding the option to set a background color in config to handle these possibility.
![image](https://user-images.githubusercontent.com/38975058/81398237-204faa80-9129-11ea-80e8-3e9d518717a7.png)
![image](https://user-images.githubusercontent.com/38975058/81398257-2b0a3f80-9129-11ea-8d72-56d840927bc0.png)

I'm doing some test and it is ok i'll push an update version
Thanks.

**Comment by michelebossa** [comment]
V 0.10 relased
