### ISSUE TITLE
Feature Request: Filter entities

### ISSUE THREAD

**Issue by aniceberg** [michelebossa/HA-Scheduler#5]
Please add the ability to filter entities in the drop-down selection box by simply typing the entity name.

**Comment by michelebossa** [comment]
Hi,
I have added the filter.
![image](https://user-images.githubusercontent.com/38975058/87175244-ae3a4400-c2d8-11ea-87b6-a46620c29c42.png)

I'm moving the code to the the next version.

Thanks
