### ISSUE TITLE
Bug fix: Adding multiple entities

### ISSUE THREAD

**Issue by aniceberg** [michelebossa/HA-Scheduler#6]
When adding multiple entities, it refreshes the page and clears the current selected entities (unless you first saved the schedule, and reopen it to add more entities). (Behavior should retain those selected entities at least temporarily?)

**Comment by michelebossa** [comment]
Hi,
I undestand the problem but to avoid this i need to rewrite a lot of interface part with some trouble added to ingrees functionality of Hassio.

At moment i din't try to avoid this problem.
Thanks
