### ISSUE TITLE
setting dimmer brightness value

### ISSUE THREAD

**Issue by IsaacBreuer** [michelebossa/HA-Scheduler#7]
hi would there be possible to set the brightness value of a light same as we do with temperature?

**Comment by michelebossa** [comment]
Hi,
Thanks for the feedback i have implemented your request but i'd like to do some test if it is ok tomorrow i'll push another release.

Example 17:05:00:B60 turn on with 60% of brightness 

Thanks.

**Comment by michelebossa** [comment]
Added by version 0.14
