### ISSUE TITLE
Call any service?

### ISSUE THREAD

**Issue by giggo** [michelebossa/HA-Scheduler#9]
Ciao, do you plan to add calling any automation (Settings/automations) or scripts (Settings/scripts) rather than just the switch_on or switch_off service?

**Comment by michelebossa** [comment]
Hi,
Can you explain better your request? At moment we can turn on or turn off an automation/script.

Thanks

**Comment by giggo** [comment]
Apologies. I missed it. Good to know.

**Comment by michelebossa** [comment]
No problem
